import type {Metadata} from "next";
import "./styles/global.css";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";

const inter = {subsets: ["latin"]};

// document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
//   anchor.addEventListener("click", function (e) {
//     e.preventDefault();

//     document.querySelector(this.getAttribute("href")).scrollIntoView({
//       behavior: "smooth",
//     });
//   });
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="navbar">
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
